FROM java:8-jre
WORKDIR usr/src
ADD ./target/orchestrationservice-0.0.1-SNAPSHOT.jar /usr/src/orchestrationservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","orchestrationservice-0.0.1-SNAPSHOT.jar"]